### PR TITLE
Remove unchecked spawn functions

### PR DESCRIPTION
**Pull request by ghost**
This PR removes two niche functions:

* `builder_spawn_unchecked`
* `spawn_unchecked`

Judging by GitHub searches, the first one seems to be completely unused, while the second one is used in two instances. The [first one](https://github.com/Nyrox/raytracer-rs/blob/52f1f3929556268157004a30c4b7b3fdc847540e/src/raytracer/raytracer.rs) can be easily rewritten using scopes, while the [second one](https://github.com/pedrocr/syncer/blob/221b6f49de9f3d4a9d4d016084002b35ce9bffda/src/backingstore/blobstorage.rs) is more difficult for me to evaluate. @pedrocr Do you think `crossbeam::scope` could replace `spawn_unchecked` in your use case?

My motivation for removing these two functions is just general cleanup - I'd like to remove as much old cruft as possible and try to bring the Crossbeam crates to a more mature state.

### CODE REVIEW

**Comment by pedrocr** [comment]
@stjepang the reason for that may be this issue in the fuse library:

https://github.com/wfraser/fuse-mt/issues/26

It's definitely fixable by making that interface better so threads are easier to integrate into the filesystem but neither me nor @wfraser have worked on it so far.

**Comment by stjepang** [comment]
> This would allow us to remove most of the unsafe code lines and all the extra allocation for results and closures.

While that would be nice, I don't think anyone would measurably benefit from it because spawning threads is already a very expensive operation itself. :)

> I've opened an issue at rust-lang didn't get much attention. Maybe a full RFC with some backing might get more traction, what do you think?

My feeling is this is such a rarely useful function that no one finds it worth adding to stdlib.

**Review by jeehoonkang — APPROVED** [review]
Hmm, I guess your motivation to remove those functions is the complexity of their specifications, right?  In that case, I'm okay with this change.

Thank you!

**Review by Vtec234 — APPROVED** [review]
Negative diffs are usually good :)

**Pull request merged**
