### PR TITLE
Remove Scope::defer

### PR DESCRIPTION
**Pull request by stjepang**
This method doesn't seem useful and isn't really used in practice. In addition to that, it causes [confusion](https://github.com/crossbeam-rs/crossbeam/issues/92). A better alternative would be `scopeguard::defer!`.

Closes https://github.com/crossbeam-rs/crossbeam/issues/92

### CODE REVIEW

**Comment by jeehoonkang** [comment]
I think it's a little bit early to remove `defer()`.  It's like RCU's `call_rcu()`, and it's quite widely used in Linux.  So I'd like to further discuss the use cases of `defer()` before removing it.

**Comment by stjepang** [comment]
This code:

```rust
// A
crossbeam::scope(|scope| {
    // B
    scope.defer(foo);
    // C
});
// D
```

Is literally equivalent to:

```rust
// A
{
    // B
    defer! { foo() }
    // C
}
// D
```

The only peculiarity that might arise is how `foo()` gets ordered with regards to scoped thread joins.

**Comment by jeehoonkang** [comment]
In the current semantics, you're right, but I think we want to generalize `Scope` in a way that scoped guards cannot replace `defer()`.  In https://github.com/crossbeam-rs/crossbeam/issues/173, we discussed such a generalization in which you can send a `scope` to another thread.  If it's implemented, `scope.defer()` called in another thread cannot be emulated by scoped guards.


Your example enlightens me on the semantics of `defer()`.  I think deferred functions should be executed **before** joining unjoined threads.  This is not only for matching with the semantics of scoped guards, but also for dealing with the case that a handle is joined in a deferred function.  Concretely, see the following example:
```rust
scope(|scope| {
    let handle = scope.spawn(|| ());
    scope.defer(|| handle.join().unwrap());
}).unwrap();
```

Related https://github.com/crossbeam-rs/crossbeam/issues/92: we previously said that threads are joined before deferred functions are executed, but I think it should be the other way.
Related #32: I added a test for this case and fix the semantics as discussed in this comment.

**Comment by stjepang** [comment]
> If it's implemented, scope.defer() called in another thread cannot be emulated by scoped guards.

> we previously said that reads are joined before deferred functions are executed, but I think it should be the other way.

Suppose deferred functions are executed first and then all threads are joined. What happens if a scoped thread calls `scope.defer()` at the moment the scope is exiting and joining all threads? Should such deferred functions be executed or not? If so, when? :)

**Comment by stjepang** [comment]
No need - #32 already removes `defer` so this would just create merge conflicts.

**Pull request closed without merging**
